### ISSUE TITLE
Chat did not work

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu_CATA#12]
Seems the spells for languages is not handled in the correct way (Did we miss some field changes?)
![chat_error](http://i.imgur.com/K9NZIY7.jpg)

**Comment by aaron02** [comment]
Fixed now

**Comment by Zyres** [comment]
https://github.com/AscEmu/AscEmu_CATA/commit/147f92b7ec627112f9b71231136e78d7a0a0e123
