### ISSUE TITLE
No interaction with GO/NPCs

### ISSUE THREAD

**Issue by Zyres** [AscEmu/AscEmu_CATA#2]
Seems this is related to #1 Seems the player is ignored.

**Comment by aaron02** [comment]
i found out that its a issue with movement or something like that because it checks creature for distance 100 to avoid guid hacks. in starting zone human the vendors have a distance to player of 2684354560

**Comment by aaron02** [comment]
Problems with updating x y z of player and incorrect locations x y z

**Comment by Zyres** [comment]
Check out #1 (in my opinion this is the main problem)

**Comment by aaron02** [comment]
Is working now update opcodes to get other feautures( gossip , auctionhouse , quest ... )
