### ISSUE TITLE
Movement

### ISSUE THREAD

**Issue by RAlexis** [AscEmu/AscEmu_CATA#29]
Movement only works for you, not for other players. Check read/write movement info functions in Unit.cpp because you're using local guid and transport guid, and not the ones in MovementInfo class. I tried using those and then it doesn't work, you just jump all over the place, my guess is there's a wrong packet structure. Sniffed the paccket with wowpacketparser but it's right so idk what might cause this.

**Comment by aaron02** [comment]
You mean go online with 2 accounts or possing a other player ?

**Comment by aaron02** [comment]
I saw yesterday that i cant go online witz 2 characters

**Comment by RAlexis** [comment]
For me it works, on my fork.
I mean this: https://github.com/AscEmu/AscEmu_CATA/blob/master/src/world/Unit.cpp#L8874
When you write movement info, you write a garbage value, because you don't initialize that guid.
If you put ObjectGuid guid = GetGuid(); instead or whatever it won't work, your client will go crazy but it won't crash, even though it's the right thing to do. Maybe @Zyres could help us out a bit.

**Comment by Zyres** [comment]
It seems there is a general confusion about ObjectGuid and WoWGuid...
Mangos based systems use ObjectGuid, if you want to work with ObjectGuid you should remove WoWGuid and replace it with ObjectGuid entirely.

**Comment by RAlexis** [comment]
There's no confusion, mate. ObjectGuid basically splits the guid which is 64 bits into 8 bytes. That is not a problem.
Also packet strucutre is a bit wrong, https://github.com/AscEmu/AscEmu_CATA/blob/master/src/world/Unit.cpp#L9010 here it should be int8. Changed it, still doesn't work.

Unit::read movement info also wrong, you have uint8 guid[8] defined there, you can remove it, so it goes into class MovementInfo::guid

**Comment by Zyres** [comment]
@RAlexis Can't help you. Seems we are not working on the same version.

**Comment by RAlexis** [comment]
I can use AscEmu if you want, but the problem is the same mate... It's not about my fork, it's about the fact that structure is wrong.

**Comment by aaron02** [comment]
@RAlexis use AscEmu we need to clean up the structures. We should work in a team and track the issues and fix them maybe you get in the cata team @Zytes. or make prs its better when we work on the same source then we get no confusion i like your work we should work together

**Comment by aaron02** [comment]
I get stuck in the login screen when logging in with 2 characters

**Comment by Zyres** [comment]
@aaron02 it is not up to me to decide about the teaminvitation of @RAlexis. It is up to RAlexis to join the team.

**Comment by RAlexis** [comment]
Sorry guys, but I don't think I'll be working again on AscEmu or ArcEmu for that matter. Not right now anyways, I'm kinda busy and I've got a lot of exams coming up and so on. I might jump in later but right now I simply can't...

**Comment by aaron02** [comment]
Fixed now ;)
